# Run: wrangler kv:namespace create CARTELERA_SUBS / CARTELERA_SNAPSHOTS to get IDs.
# Set secret: wrangler secret put RESEND_API_KEY

name = "cartelera-proxy"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["0 8 * * *"]

[[kv_namespaces]]
binding = "CARTELERA_SUBS"
id = "060bce2011564bf59da4e2178a925e6c"

[[kv_namespaces]]
binding = "CARTELERA_SNAPSHOTS"
id = "46fa48b250524b4d986b39647c95e66f"
