const CARTELERA_IDS = {
  "Anatomía A": 32, "Anatomía B": 4, "Anatomía C": 68,
  "Bioética": 66, "Biología": 1,
  "Bioquímica Clínica I": 9, "Bioquímica Clínica II": 8,
  "Bioquímica y Biología Molecular": 58,
  "Ciencias Exactas": 5, "Ciencias Sociales y Medicina": 76,
  "Cirugía A": 3, "Cirugía B": 64, "Cirugía C": 67, "Cirugía D": 19,
  "Cirugía de Tórax": 78, "Cirugía E": 22,
  "Citología, Histología y Embriología": 26,
  "Deontología Médica y Medicina Legal": 33,
  "Dermatología": 20,
  "Diagnóstico y Terapéutica por Imágenes": 74,
  "Discapacidad Intelectual": 89,
  "Ecología Humana y Promoción de la Salud": 56,
  "Educación para la Salud": 57,
  "El paciente con enfermedad crónica de alto impacto familiar": 83,
  "Enfermedades Poco Frecuentes en Medicina": 88,
  "Epidemiología": 84,
  "Farmacología Aplicada": 23, "Farmacología Básica": 69,
  "Filosofía Médica": 65,
  "Fisiología y Física Biológica": 21,
  "Genética": 35,
  "Ginecología A": 30, "Ginecología B": 25,
  "Historia de la Medicina": 73,
  "Infectología": 29,
  "Informática Básica": 79, "Informática Médica": 77,
  "Inglés Médico": 82,
  "Inmunología": 27,
  "Literatura, Cine y Medicina": 72,
  "Medicina General y Familiar": 204,
  "Medicina Interna A": 60, "Medicina Interna B": 24, "Medicina Interna C": 63,
  "Medicina Interna D": 7, "Medicina Interna E": 70, "Medicina Interna F": 61,
  "Microbiología y Parasitología": 6,
  "Neuroanatomía Semiológica": 85,
  "Neurocirugía": 206, "Neurología": 80,
  "Obstetricia": 17,
  "Oftalmología": 34,
  "Ortopedia y Traumatología": 37,
  "Otorrinolaringología": 36,
  "Patología A": 71, "Patología B": 18,
  "Pediatría A": 11, "Pediatría B": 16,
  "Psicología Médica": 62, "Psiquiatría": 31,
  "Salud Ambiental": 54, "Salud Pública": 75, "Salud y Medicina Comunitaria": 55,
  "Seminarios de Investigación Científica": 87,
  "Terapia Intensiva": 28, "Toxicología": 10,
  "Trasplante de Órganos": 81,
  "Urología": 38
};
